---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Insatall Apache.
      yum: name={{ item }} state=present
      with_items:
      - httpd
      - php
      - ph-mysql
    - name: Download Wordpress
      get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/ww/html/wordpress.tar.gz force=yes
    - name: Extract Wordpress
      command: "tar xzf /var/ww/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
    - name: make directory tree readable
      file:
        path: /var/www/html
        mode: u=rwX,g=rX,o=rX
        owner: apache
        group: apache
    - name: Make sure Apache is started now and at the boot
      service: name=httpd state=started enabled=yes
